### PR TITLE
Alpine Linux docker container support and bindstr adjustment for better communication with windows

### PR DESCRIPTION
**Pull request by ramijebara**
## What & Why

This PR contains two suggested changes. These changes represent an integration of existing community work that I have tested myself over the last few months. 

1. Alpine Linux docker container support. The Debian slim based container usually fails compliance scans due to outdated packages or known vulnerabilities. Alpine is more lightweight and will pass compliance container scans more often then not. 

2. Added sign, seal to the bindstr variable, to samba/lib/com/dcom/main.c. Based on my experience,  communication with newer versions of windows is much more reliable. queries that fail with the un-patched code work with this change.

Just contributing back to upstream & community. I hope you find this work useful.

### CODE REVIEW

**Comment by ArnoStiefvater** [comment]
Hey @ramijebara ,

Thanks a lot for your contribution!

Can you please make a separate PR for the second suggestion (commit adding the [sign,seal] to the samba/lib/com/dcom/main.c)?

Reviewing your first suggestion will unfortunately take a lot longer than reviewing your second suggestion.

**Comment by ramijebara** [comment]
@ArnoStiefvater thanks a lot for taking a look. I will make two separate PRs as suggested. I will close this PR in the mean time.

**Comment by bjoernricks** [comment]
Two cents from my side, we wont replace the base debian slim container image with alpine. We could provide an alpine image additionally if somebody is willing to maintain it.

**Comment by ramijebara** [comment]
Separate PRs created. @ArnoStiefvater

**Pull request closed without merging**
